site_name: Programming Crash Course
site_url: https://scott-cjx.github.io/Programming-Crash-Course/
repo_name: scott-cjx/Programming-Crash-Course
repo_url: https://github.com/scott-cjx/Programming-Crash-Course

theme:
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  name: material
  features:
    - content.tabs.link
    - navigation.instant
  icon:
    repo: fontawesome/brands/git-alt 


markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


nav:
  - Home: README.md
  - Github: github/README.md
  - VSCode: vscode/README.md
  - Basics:
    - Home: basics/README.md
    - Variables: basics/variables.md
    - Arithmetics: basics/arithmetic.md
    - Control Flow: basics/control-flow.md

  - Python: python/README.md

