site_name: Programming Crash Course
site_url: https://scott-cjx.github.io/Programming-Crash-Course/
theme:
  name: material
  features:
    - content.tabs.link
    - navigation.instant

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


nav:
  - Home: README.md
  - Github: github/README.md
  - VSCode: vscode/README.md
  - Basics:
    - Home: basics/README.md
    - Variables: basics/variables.md
    - Arithmetics: basics/arithmetic.md
    - Control Flow: basics/control-flow.md

  - Python: python/README.md
  
