site_name: Programming Crash Course
site_url: https://scott-cjx.github.io/Programming-Crash-Course/
theme:
  name: material
  features:
    - content.tabs.link

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: README.md
  - Github: github/README.md
  - VSCode: vscode/README.md
  - Python: python/README.md
  
